
from descriptors import ModelGeneratorDoc, ModelMessageDescriptor
from string_writer import StringWriter

class ImportWriter():
    
    def __init__(self, doc: ModelGeneratorDoc):
        self._doc = doc
        pass
    
    def write(self, wr: StringWriter) -> StringWriter:
        wr.writeln(
            'from __future__ import annotations',
            'from typing import Optional, List, Any',
            'from dataclasses import dataclass, asdict',
            'from enum import Enum',
        )
        # additional import added to docs will be added here
        self._write_header(wr)
        return wr

    def _write_header(self, wr: StringWriter):
        wr.writeln(
            '"""',
            'auto generated file, model classes generated from protobuf classes',
            'example of usage:',
            '',
            'from google.protobuf.json_format import MessageToDict',
            '# proto buf message',
            'pbMsg = pb2.MyMessage(...)',
            '# convert to autogenerated Model object',
            'modelMsg = ModelMyMessage.from_dict(MessageToDict(pbMsg))',
            '"""',
        )