# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ileservice.proto\x12\nfileupload\"0\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x12\n\nchunk_size\x18\x02 \x01(\x05\"0\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2N\n\x0b\x46ileService\x12?\n\nUploadFile\x12\x15.fileupload.FileChunk\x1a\x18.fileupload.UploadStatus(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fileservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILECHUNK._serialized_start=33
  _FILECHUNK._serialized_end=81
  _UPLOADSTATUS._serialized_start=83
  _UPLOADSTATUS._serialized_end=131
  _FILESERVICE._serialized_start=133
  _FILESERVICE._serialized_end=211
# @@protoc_insertion_point(module_scope)
