# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x07jk_test\"|\n\x04\x46ooA\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x12.jk_test.ValueTypeH\x02\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_valueB\x07\n\x05_type\"\x12\n\x04\x46ooB\x12\n\n\x02id\x18\x01 \x01(\t\"\x99\x03\n\x04\x46ooC\x12\x0c\n\x04id_b\x18\x01 \x01(\t\x12\x13\n\x06name_b\x18\x02 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07value_b\x18\x03 \x01(\x05H\x03\x88\x01\x01\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x12.jk_test.ValueTypeH\x04\x88\x01\x01\x12+\n\x05\x65xtra\x18\x05 \x01(\x0e\x32\x1c.jk_test.FooC.ValueTypeExtra\x12\x1d\n\x06others\x18\x06 \x03(\x0b\x32\r.jk_test.FooA\x12\x1d\n\x04\x66ooA\x18\x65 \x01(\x0b\x32\r.jk_test.FooAH\x00\x12\x1d\n\x04\x66ooB\x18\x66 \x01(\x0b\x32\r.jk_test.FooBH\x00\x12\x0f\n\x04\x66ooC\x18\xc9\x01 \x01(\tH\x01\x12\x0f\n\x04\x66ooD\x18\xca\x01 \x01(\x05H\x01\x12\x0c\n\x04last\x18\x07 \x01(\x05\"5\n\x0eValueTypeExtra\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06TYPE_C\x10\x01\x12\n\n\x06TYPE_D\x10\x02\x42\x12\n\x10ThisOrThatChoiceB\x0c\n\nAorBChoiceB\t\n\x07_name_bB\n\n\x08_value_bB\x07\n\x05_type\"\x9a\x01\n\x0e\x46ooFromCoPilot\x12*\n\x03\x62\x61r\x18\x01 \x01(\x0b\x32\x1b.jk_test.FooFromCoPilot.BarH\x00\x12*\n\x03\x62\x61z\x18\x02 \x01(\x0b\x32\x1b.jk_test.FooFromCoPilot.BazH\x00\x1a\x12\n\x03\x42\x61r\x12\x0b\n\x03\x66oo\x18\x01 \x01(\x05\x1a\x12\n\x03\x42\x61z\x12\x0b\n\x03\x66oo\x18\x02 \x01(\tB\x08\n\x06\x63hoice*0\n\tValueType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06TYPE_A\x10\x01\x12\n\n\x06TYPE_B\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUETYPE._serialized_start=738
  _VALUETYPE._serialized_end=786
  _FOOA._serialized_start=23
  _FOOA._serialized_end=147
  _FOOB._serialized_start=149
  _FOOB._serialized_end=167
  _FOOC._serialized_start=170
  _FOOC._serialized_end=579
  _FOOC_VALUETYPEEXTRA._serialized_start=460
  _FOOC_VALUETYPEEXTRA._serialized_end=513
  _FOOFROMCOPILOT._serialized_start=582
  _FOOFROMCOPILOT._serialized_end=736
  _FOOFROMCOPILOT_BAR._serialized_start=688
  _FOOFROMCOPILOT_BAR._serialized_end=706
  _FOOFROMCOPILOT_BAZ._serialized_start=708
  _FOOFROMCOPILOT_BAZ._serialized_end=726
# @@protoc_insertion_point(module_scope)
