# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import test_pb2 as test__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FooGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getFoo = channel.unary_unary(
                '/jk_test.FooGrpc/getFoo',
                request_serializer=test__pb2.FooRequest.SerializeToString,
                response_deserializer=test__pb2.FooResponse.FromString,
                _registered_method=True)


class FooGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getFoo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FooGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getFoo': grpc.unary_unary_rpc_method_handler(
                    servicer.getFoo,
                    request_deserializer=test__pb2.FooRequest.FromString,
                    response_serializer=test__pb2.FooResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jk_test.FooGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jk_test.FooGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FooGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getFoo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jk_test.FooGrpc/getFoo',
            test__pb2.FooRequest.SerializeToString,
            test__pb2.FooResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
