# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x07jk_test\"|\n\x04\x46ooA\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x12.jk_test.ValueTypeH\x02\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_valueB\x07\n\x05_type\"\x12\n\x04\x46ooB\x12\n\n\x02id\x18\x01 \x01(\t\"\x99\x03\n\x04\x46ooC\x12\x0c\n\x04id_b\x18\x01 \x01(\t\x12\x13\n\x06name_b\x18\x02 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07value_b\x18\x03 \x01(\x05H\x03\x88\x01\x01\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x12.jk_test.ValueTypeH\x04\x88\x01\x01\x12+\n\x05\x65xtra\x18\x05 \x01(\x0e\x32\x1c.jk_test.FooC.ValueTypeExtra\x12\x1d\n\x06others\x18\x06 \x03(\x0b\x32\r.jk_test.FooA\x12\x1d\n\x04\x66ooA\x18\x65 \x01(\x0b\x32\r.jk_test.FooAH\x00\x12\x1d\n\x04\x66ooB\x18\x66 \x01(\x0b\x32\r.jk_test.FooBH\x00\x12\x0f\n\x04\x66ooC\x18\xc9\x01 \x01(\tH\x01\x12\x0f\n\x04\x66ooD\x18\xca\x01 \x01(\x05H\x01\x12\x0c\n\x04last\x18\x07 \x01(\x05\"5\n\x0eValueTypeExtra\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06TYPE_C\x10\x01\x12\n\n\x06TYPE_D\x10\x02\x42\x12\n\x10ThisOrThatChoiceB\x0c\n\nAorBChoiceB\t\n\x07_name_bB\n\n\x08_value_bB\x07\n\x05_type\"\x9a\x01\n\x0e\x46ooFromCoPilot\x12*\n\x03\x62\x61r\x18\x01 \x01(\x0b\x32\x1b.jk_test.FooFromCoPilot.BarH\x00\x12*\n\x03\x62\x61z\x18\x02 \x01(\x0b\x32\x1b.jk_test.FooFromCoPilot.BazH\x00\x1a\x12\n\x03\x42\x61r\x12\x0b\n\x03\x66oo\x18\x01 \x01(\x05\x1a\x12\n\x03\x42\x61z\x12\x0b\n\x03\x66oo\x18\x02 \x01(\tB\x08\n\x06\x63hoice\",\n\nFooRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0b\x46ooResponse\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t*0\n\tValueType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06TYPE_A\x10\x01\x12\n\n\x06TYPE_B\x10\x02\x32@\n\x07\x46ooGrpc\x12\x35\n\x06getFoo\x12\x13.jk_test.FooRequest\x1a\x14.jk_test.FooResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUETYPE']._serialized_start=831
  _globals['_VALUETYPE']._serialized_end=879
  _globals['_FOOA']._serialized_start=23
  _globals['_FOOA']._serialized_end=147
  _globals['_FOOB']._serialized_start=149
  _globals['_FOOB']._serialized_end=167
  _globals['_FOOC']._serialized_start=170
  _globals['_FOOC']._serialized_end=579
  _globals['_FOOC_VALUETYPEEXTRA']._serialized_start=460
  _globals['_FOOC_VALUETYPEEXTRA']._serialized_end=513
  _globals['_FOOFROMCOPILOT']._serialized_start=582
  _globals['_FOOFROMCOPILOT']._serialized_end=736
  _globals['_FOOFROMCOPILOT_BAR']._serialized_start=688
  _globals['_FOOFROMCOPILOT_BAR']._serialized_end=706
  _globals['_FOOFROMCOPILOT_BAZ']._serialized_start=708
  _globals['_FOOFROMCOPILOT_BAZ']._serialized_end=726
  _globals['_FOOREQUEST']._serialized_start=738
  _globals['_FOOREQUEST']._serialized_end=782
  _globals['_FOORESPONSE']._serialized_start=784
  _globals['_FOORESPONSE']._serialized_end=829
  _globals['_FOOGRPC']._serialized_start=881
  _globals['_FOOGRPC']._serialized_end=945
# @@protoc_insertion_point(module_scope)
